LadyBugML/ladybug

backend/services/preprocess_source_code.py

Added preprocess_source_code.py, a script that preprocesses all source code files under a given directory. The function outputs a list of tuples for each file of the form:
(<file_path>,<file_name>,<preprocessed_file_content>)
Closes [LB-62](https://ladybug-ai.atlassian.net/browse/LB-62)
[LB-62]: https://ladybug-ai.atlassian.net/browse/LB-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LB-62] Implement Source Code Preprocessing

---

backend/app/api/routes.py
backend/index.py

Also changed local db flag to use environment variable

Refactor Routes file to consolidate duplicated code and reorganized in a more comprehensive manner

---

backend/app/api/routes.py
backend/services/preprocess_source_code.py
backend/tests/test_preprocess_source_code.py

Integrate the preprocessing for repos and print repo file paths from root. Package access changes in @tachille4's code.

[LB-77] Update-routes-to-use-real-preprocessing

---

backend/index.py

Creating a wrapper function in `index.py` will allow us to instantiate a Flask app for use in unit testing. This won’t impact running `index.py`.

[LB-86] Create wrapper factory function for Flask app creation

---

backend/database/database.py
backend/index.py

Fixed some database issues

---

backend/app/api/routes.py
backend/services/filter.py

The process running did not have permissions to access and delete files on Windows machines. It should now.

Fixed issue with running service on Windows machines

---

backend/app/api/routes.py
backend/database/database.py

The helper function gets all the code file's embeddings from a repo

Added helper function

---

backend/app/api/routes.py
backend/services/preprocess.py
backend/services/preprocess_source_code.py

**Overview**
This PR fixes an issue observed when hitting the /initialization endpoint: The BugLocalization class would be initialized on each source code file in a repository. Additionally fixes encoding error found when creating embeddings for preprocessed source code files.
**Changes Made**
- routes.py: Removed unnecessary bug_localizer object
- preprocess.py: Added init function
- preprocess_source_code.py: Added encoding option for UTF-8

[LB-101] Fix Nested BugLocalizer Initialization

---

backend/app/api/routes.py

**Overview**
This PR fixes a bug where embeddings are duplicated if a GitHub repository was re-initialized. 
The bug arises because `replace_one` inserts a new document with `null` for the `repo_id` field when the `repo_id` field is not yet properly set during the first loop iteration. This is because `upsert=True` allows the operation to insert a new document if the filter condition is not met, and the `repo_id` isn't initialized correctly at that point.
**Changes Made**
- Switch to `replace_one` over `update_one`
- Retrieve the entire `repo` document and access its `id` field
**Testing Strategy**
1. Ran `/initialization` and checked the database to ensure everything was populated correctly the first time
2. Re-ran `/initialization` without making any modifications to the database
3. …

[LB-100] Fix duplicate embeddings documents on re-initializations

---

README.md
backend/app/api/routes.py
probot/index.js

Resolved postman issues so now no need to use commentID

Lb 93 update probot responses on initialization for better user experience

---

backend/app/api/routes.py
backend/database/database.py
backend/tests/test_database.py
requirements.txt

**Overview**
This PR integrates `build_corpus()`, `get_boosted_files()`, and `reorder_rankings()` into the `report()` endpoint and also adds functionality to fetch corpus embeddings from the database. A new test file for database functions was also created.
**Changes Made**
* Add aforementioned functions to `report()`
* Add comments to easily distinguish steps in the report pipeline
* Create new database function to fetch embeddings if they exist in the corpus
* Create new database test file that creates a mock database with mock collections to test database functions.
**Testing Strategy**
* Used new unit tests
* Integration tests have not been done on `report()` yet!!

[LB-123 + LB-124] Integrate new GUI functions into pipeline and fetch corpus embeddings from DB

---

backend/app/api/routes.py
backend/services/preprocess_bug_report.py

This PR fixes the following bugs that were in query expansion:
- JSON download link included in bug report contents
- resourceids aren’t preprocessed correctly
**Changes Made**
- preprocess_bug_report.py: Add regex matching to remove JSON attachment links
- routes.py: nit change, rename query_embeddings to corpus_embeddings
Testing:
Live issues

[LB-69] Fix Query Expansion Bugs

---

Dockerfile.backend
docker-compose.yml

Dockerized ladybug

---

backend/index.py

TECH DEBT GONE

---

backend/app/api/routes.py
backend/services/extract_gui_data.py

This PR allows user to submit an issue without a trace or with an incomplete trace. In either case, rankings are calculated without GUI augmentation or filtering & boosting. 
Changes made:
- `extract_gui_data.py`: Added JSON string null checks on `extract_sc_terms` & extract_gs_terms
`routes.py`: 
-  Added GUI_DATA flag
- Added `fetch_all_embeddings` & `fetch_corpus_embeddings` to handle separate cases
Testing: Live testing all three test cases
Invalid trace: https://github.com/tachille4/ladybug-data-android/issues/150
Incomplete trace: https://github.com/tachille4/ladybug-data-android/issues/149
Valid trace: https://github.com/tachille4/ladybug-data-android/issues/148

[LB-138] Fix For No execution.json Trace in the Issue Body.

---

backend/app/api/routes.py
probot/index.js

This pull request includes changes to improve the consistency and readability of status messages sent to Probot, as well as enhancements to the comment updating mechanism in the Probot app.
Improvements to status messages:
* [`backend/app/api/routes.py`](diffhunk://#diff-ae6170e4135656d8315f5682d50fdc16b1cc40efa1454c9a6bc2e305fa0199e5L98-R98): Updated various status messages sent to Probot to use a consistent checkmark emoji "✅" instead of various other emojis. [[1]](diffhunk://#diff-ae6170e4135656d8315f5682d50fdc16b1cc40efa1454c9a6bc2e305fa0199e5L98-R98) [[2]](diffhunk://#diff-ae6170e4135656d8315f5682d50fdc16b1cc40efa1454c9a6bc2e305fa0199e5L116-R116) [[3]](diffhunk://#diff-ae6170e4135656d8315f5682d50fdc16b1cc40efa1454c9a6bc2e305fa0199e5L171-R171) …

Append checklist instead of edits

---

backend/services/db_service.py
backend/services/initialization_service.py
backend/services/messenger_service.py
backend/services/report_service.py
backend/services/worker_service.py
probot/index.js

The main change is replacing direct calls to `send_update_to_probot` with a new `ProbotMessenger` class to centralize message sending and reduce code bloat. I also resolved the duplicate introduction message by replacing it with a unique comment.
Refactoring messaging system:
* [`backend/services/db_service.py`](diffhunk://#diff-650a9069f01705628a2cee45d362b333975f8137bdec230e364fbd8be5e263acL4-L70): Replaced `send_update_to_probot` calls with `ProbotMessenger` class instances to handle messaging.
* [`backend/services/initialization_service.py`](diffhunk://#diff-fff6924748ad1183e6f0d4ed4cb7f42324ae3e3b4f15f8d6e2ea69337e22b069L4-R54): Updated the `initialize` and `process_and_store_embeddings` functions to use `ProbotMessenger` for sending status updates.
* …

Probot user and developer quality of life

---

README.md

Added a new section for Red Wing, a local testing and metrics tool designed for Ladybug, detailing its purpose, features, and usage instructions.

Update README with redwing

---

backend/red_wing/cli_helpers.py
backend/red_wing/localization.py

**Overview**
This PR adds effectiveness metrics to the metrics summary at the end of Redwing execution. Metrics include best, worst, and average effectiveness. Effectiveness is simply the highest ranking buggy file for a given code repository.
Below are the results after running Redwing on all 80 repos.

[LB-176] Implement effectiveness metrics

---

.gitignore
backend/red_wing/cli_helpers.py
backend/red_wing/localization.py

This pull request introduces several enhancements to the `backend/red_wing` module, focusing on adding new metrics for evaluating buggy file rankings and improving code readability.
* Added import for `mrr_at_k` in `backend/red_wing/cli_helpers.py`.
* Introduced Mean Reciprocal Rank (MRR) calculations at various levels (50, 25, 10, 5, 1) in the `output_metrics` function. [[1]](diffhunk://#diff-16ee2f5595afd2ce7035a9b23e6f6402a92a89ae7348ef0465e7482b04960f0bR68-R73) [[2]](diffhunk://#diff-16ee2f5595afd2ce7035a9b23e6f6402a92a89ae7348ef0465e7482b04960f0bR83-R95)
* Displayed MRR metrics in a new table format within the console output.
* Added missing newline characters between function definitions in `backend/red_wing/localization.py`. …

[LB-147] Implement Redwing MRR Metric

---

backend/red_wing/localization.py

This PR fixes Redwing rankings for Windows by normalizing file paths to a linux format.

[LB-179] Fix Redwing on Windows

---

backend/red_wing.py
backend/red_wing/cli_helpers.py
backend/red_wing/localization.py

This pull request implements the relative improvement metric calculation into Redwing. It adds two new flags to the CLI tool:
-  -b: Runs Redwing without GUI augmentation
-  -m: Runs Redwing in improvement mode, which does a full run with GUI augmentation, then another without augmentation to calculation relative improvement.
In the improvement mode, redwing outputs the Hits@10 for both base and enhance runs.
```
Relative Improvement Metrics
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Metric                    ┃ Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ Relative Improvement @ 10 │ 0.056 │
└───────────────────────────┴───────┘
BASE HITS AT 10
┏━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Metric         ┃ Value ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ Base Hits @ 10 │  54   │
└────────────────┴───────┘
ENHANCED …
```

[LB-175] Redwing Relative improvement

---

backend/experimental_unixcoder/bug_localization.py
backend/red_wing.py
backend/red_wing/cli_helpers.py
backend/red_wing/localization.py
backend/updated_dataset_builder.py

A large feature branch that focuses around implementing a model selector into Redwing. This comes with large sweeping changes to bug_localization.py due to the nature of allowing multiple models to run the same code.
Currently it comes with the Hugging Face models
- Salesforce/codet5p-110m-embedding
- Microsoft/UniXcoder-base
Also converts the BugLocalization class into a singleton in order to support maintaining a single selected model rather than defaulting to the previous UniXcoder. and implements method-level chunking.
Additionally fixes the BigMetrics.csv by storing them to their own specified directory backend/metrics/big following name format:
<Model>-<# of repos>repos-<# of loops>loops-<base OR improvement>.csv

Re-implement model selector removing experimental pieces
